name: Lint
on:
  pull_request:
    branches:
      - main
      - 'feature/*'
    paths-ignore:
      - '**.md'
  push:
    branches:
      - main
      - 'feature/*'
    paths-ignore:
      - '**.md'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: 'package.json'
      - name: Install Yarn v4
        run: |
          yarn set version berry
      - name: Get pnpm store directory
        id: pnpm-cache
        run: |
          echo "::set-output name=pnpm_cache_dir::$(pnpm store path)"
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.pnpm_cache_dir }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies.
        run: pnpm install
      - name: Test
        run: pnpm run test
      - name: Build
        run: pnpm run build
